=== salmaneaaboud/ETHAZI_2024/LM/HITO_4_1/EJERCICIO3/ejercicio3.dtd
<!ELEMENT facturas (factura+)>
<!ELEMENT factura (num_linea,cod_cliente,articulo)>
<!ELEMENT num_linea (#PCDATA)>
<!ELEMENT cod_cliente (#PCDATA)>
<!ELEMENT articulo (cod_articulo, nombre_articulo, cantidad, precio_unitario)>
<!ELEMENT cod_articulo (#PCDATA)>
<!ELEMENT nombre_articulo (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precio_unitario (#PCDATA)>
<!ATTLIST factura facturaID CDATA #REQUIRED>

=== salmaneaaboud/ETHAZI_2024/LM/HITO_4_1/EJERCICIO3/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE facturas SYSTEM "ejercicio3.dtd">
<facturas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/D:/ETHAZI/LENGUAJES/HITO_4_1/EJERCICIO3/ejercicio3.xsd">   
        <factura facturaID="0000">     
              <num_linea>1</num_linea>     
              <cod_cliente>1</cod_cliente>     
              <articulo>       
                    <cod_articulo>0001</cod_articulo>       
                    <nombre_articulo>CD</nombre_articulo>       
                    <cantidad>2</cantidad>       
                    <precio_unitario>2200</precio_unitario>     
              </articulo>   
        </factura>     
        <factura facturaID="0001">     
              <num_linea>2</num_linea>     
              <cod_cliente>2</cod_cliente>     
              <articulo>       
                    <cod_articulo>0002</cod_articulo>       
                    <nombre_articulo>Enchufe</nombre_articulo>       
                    <cantidad>4</cantidad>       
                    <precio_unitario>2400</precio_unitario>     
              </articulo>   
        </factura>   
        <factura facturaID="0002">     
              <num_linea>3</num_linea>     
              <cod_cliente>2</cod_cliente>     
              <articulo>       
                    <cod_articulo>0003</cod_articulo>       
                    <nombre_articulo>Pilas</nombre_articulo>       
                    <cantidad>6</cantidad>       
                    <precio_unitario>2800</precio_unitario>     
              </articulo>   
        </factura> 
</facturas>
