=== salmaneaaboud/ETHAZI_2024/LM/HITO_4_1/EJERCICIO4/libro.dtd
<!ELEMENT libro (titulo, resumen, categorias, precio)>
<!ATTLIST libro
    isbn CDATA #REQUIRED
    fecha CDATA #REQUIRED
    paginas CDATA #REQUIRED
>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>
<!ELEMENT categorias (categoria+)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA #REQUIRED>

=== salmaneaaboud/ETHAZI_2024/LM/HITO_4_1/EJERCICIO4/ejercicio4.xml
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE libro SYSTEM "libro.dtd"> 
<libro isbn="isbn-861003-11-0" fecha="Noviembre 1999" paginas="750" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/D:/ETHAZI/LENGUAJES/HITO_4_1/EJERCICIO4/libro.xsd">   
      <titulo>Aprendiendo XML</titulo>   
      <resumen>Metodo de aprender XML</resumen>   
      <categorias>     
            <categoria>Internet</categoria>     
            <categoria>Publicacion Web</categoria>     
            <categoria>XML</categoria>   
      </categorias>   
      <precio moneda="eur">34.5</precio> 
</libro>
